@startuml platform-setup-sequence
start

:Setup dependency injection module;
:Check configuration;
if (Configuration is valid?) then (no)
  :Raise exception;
  end
else (yes)
endif

:Setup components references\nwith communicators and bindings;
:Launch coroutines for each component;
:Save the reference to each coroutine job;
stop
@enduml