@startuml platform-setup-sequence
start

:Setup dependency injection module;
:Check configuration;
if (Configuration is valid?) then (no)
  :Raise exception;
  end
else (yes)
endif

:Setup components references\nwith communicators and bindings;
:Lauch coroutines for each component;
:Save a reference to each coroutine job;
:Start the platform;
stop
@enduml