name: Java CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 19
    - name: Build
      run: ./gradlew build
    - name: Test
      run: ./gradlew test
