name: Compile Latex and deploy report
on:
  push:
    branches: ['master']
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    name: "Compile latex sources"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Generate tag
        id: tag-generation
        run: |
          MESSAGE=$(git log --no-merges $(git describe --tags --abbrev=0)..HEAD --oneline --pretty=format:%s)
          if ! git describe --tags --exact-match HEAD; then
            TAG="$(git describe)" || TAG="0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
          else
            TAG="$(git describe --tags --exact-match HEAD)"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build report
        uses: xu-cheng/latex-action@2.8.0
        with:
          root_file: thesis-main.tex
          args: -jobname=nicolas-farabegoli-thesis_${{ steps.tag-generation.outputs.tag }} -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.tag-generation.outputs.tag }}
          title: Release ${{ steps.tag-generation.outputs.tag }}
          prerelease: false
          files: |
            *.pdf
