name: Compile Latex and deploy report
on:
  push:
    branches: ['master']
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    name: "Compile latex sources"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Build report
        uses: xu-cheng/latex-action@2.7.0
        with:
          root_file: thesis-main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            *.pdf
